name: Cherry Pick Workflow

on:
  workflow_dispatch:
    inputs:
      source_branch:
        description: "Nombre de la rama origen para cherry-pick"
        required: true
        default: "main"
      commit_hash:
        description: "Hash del commit que quieres cherry-pick"
        required: true
      target_branch:
        description: "Nombre de la rama destino para cherry-pick"
        required: true
        default: "release"

jobs:
  cherry-pick:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Fetch source branch
        run: git fetch origin ${{ inputs.source_branch }}

      - name: Create a new branch for cherry-pick
        run: |
          git checkout ${{ inputs.target_branch }}
          git checkout -b cherry-pick/${{ inputs.commit_hash }}
          git cherry-pick ${{ inputs.commit_hash }}

      - name: Push cherry-pick branch
        run: |
          git push origin cherry-pick/${{ inputs.commit_hash }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: cherry-pick/${{ inputs.commit_hash }}
          title: "Cherry-pick: ${{ inputs.commit_hash }}"
          body: |
            Este pull request contiene el cherry-pick del commit `${{ inputs.commit_hash }}`
            desde `${{ inputs.source_branch }}` hacia `${{ inputs.target_branch }}`.
          base: ${{ inputs.target_branch }}
