name: Cherry-Pick and Deploy

on:
  workflow_dispatch:
    inputs:
      commit_id:
        description: 'ID del commit a cherry-pick'
        required: true
      branch:
        description: 'Rama desde donde se hará el cherry-pick'
        required: true
        default: 'develop'

jobs:
  cherry_pick_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        ref: ${{ inputs.branch }} # Asegúrate de revisar la rama especificada por el usuario

    - name: Fetch all branches and commits
      run: git fetch --all

    - name: Cherry-pick the commit
      run: |
        git cherry-pick ${{ inputs.commit_id }} || (echo "Cherry-pick failed!" && exit 1)

    - name: Verify cherry-pick
      run: git log -1 --oneline

    - name: Set up deployment (optional)
      run: |
        echo "Commit cherry-picked: ${{ inputs.commit_id }}"
        echo "Branch used: ${{ inputs.branch }}"

    - name: Deploy Application
      env:
        APP_ENV: production # Cambia esto según tu entorno
      run: |
        echo "Starting deployment with cherry-picked commit..."
        # Aquí va tu lógica de despliegue (Docker build, Terraform apply, etc.)
        echo "Deployment successful!"
