name: Cherry Pick Workflow

on:
  workflow_dispatch:
    inputs:
      source_branch:
        description: "Nombre de la rama origen para cherry-pick"
        required: true
        default: "main"
      commit_hash:
        description: "Hash del commit que quieres cherry-pick"
        required: true
      target_branch:
        description: "Nombre de la rama destino para cherry-pick"
        required: true
        default: "release"

jobs:
  cherry-pick:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Cherry-pick commit
        run: |
          git fetch origin ${{ inputs.source_branch }}
          git checkout ${{ inputs.target_branch }}
          git cherry-pick ${{ inputs.commit_hash }}
          git push origin ${{ inputs.target_branch }}

      - name: Push changes
        run: |
          git push origin ${{ inputs.target_branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

