name: CI

on:
  push:
    branches:
      - master
      - feature/v4

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Terraform Init
        run: terraform init
        working-directory: ./infra
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

      # Generates an execution plan for Terraform
      - name: Terraform Plan
        run: terraform plan -input=false
        working-directory: ./infra
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  

      - name: Run Unit Tests - ci
        run: |
          pip install requests pytest google-cloud-bigquery
          pip install -r backend/func1/requirements.txt 
          PYTHONPATH=. pytest tests/

